Counter({'Woo-contactpersoon': 20,
         'woo@nl': 5,
         'Woo Contactpersoon': 3,
         'contactpersoonwoo@nl': 3,
         'Woo-team': 3,
         'Woo-coördinator': 3,
         'info@nl': 2,
         'Sutman': 2,
         'Van den Oever': 2,
         'Klant Contact Centrum': 2,
         'Juridische Zaken': 2,
         'Moira Faber': 2,
         'Andrea Bouhuys': 2,
         'Team juridische zaken': 2,
         'Martijn Erbel': 2,
         'Anouschka Anepool': 2,
         'Woo contactpersoon': 2,
         'Woo-functionaris': 2,
         'Klantcontactcentrum': 2,
         'Afdeling Juridische Zaken': 2,
         'Serviceteam': 2,
         'juridisch@nl': 2,
         'Michelle Evers': 1,
         'Han Bruggink': 1,
         'Olga Marchenko': 1,
         'Bianca Vermeirsch - van de Calseijde': 1,
         'communicatieadviseur Louwerse': 1,
         'contactpersoonwoo@od-nl': 1,
         'A. Akman': 1,
         'Mathijs Aarts': 1,
         'Twan Zimmermann': 1,
         'Wim van Emmen': 1,
         'Jurist': 1,
         'Secretariaat De Waddeneilanden': 1,
         'Algemene toegang': 1,
         'Jessica Flohr': 1,
         'wetopenoverheid@nl': 1,
         'Team Jurdische Zaken': 1,
         'M.E.P. Somers': 1,
         'Team Woo': 1,
         'Coördinator cluster': 1,
         'post@nl': 1,
         'Natasja Hassankhan': 1,
         'Willem-Jan Kouwenberg': 1,
         'P.C. van Dongen': 1,
         'Woo coordinator': 1,
         'Datashop': 1,
         'woo@sozawe-nw-nl': 1,
         'Klant Contact Centrum gemeente Oss': 1,
         '': 1,
         'Félice Thenu': 1,
         'J. Gootzen': 1,
         'Ada van Wijk': 1,
         'info@i-nl': 1,
         'Marja Vink': 1,
         'woo-coordinator@nl': 1,
         'Woo contactpersoon Waterschapsbedrijf Limburg': 1,
         'D. Budak': 1,
         'Wieteke Kamps': 1,
         'Ruud Quispel': 1,
         'Liselotte Huismans': 1,
         'Jack Karelse': 1,
         'Justin Villeval': 1,
         'Jurist Samenwerking Kempengemeenten': 1,
         'Bestuurssecretariaat Samenwerking Kempengemeenten': 1,
         'Henderikus van Loon': 1,
         'Woo_Coordinator@nl': 1,
         'KCC medewerker': 1,
         'Victorien Erren-Wolters': 1,
         'College van B&W, postbus 35, 7720 AA, Dalfsen': 1,
         'Paul Berkers': 1,
         'I -coach': 1,
         'V. Vroege': 1,
         'woo@org': 1,
         'Gerard Annink': 1,
         'afdeling Dienstverlening, team Omgevingsloket': 1,
         'Team Juridische zaken, Inkoop en Subsidies': 1,
         'Sietske van der Velden': 1,
         'Nomi van Ballegooij': 1,
         'W.A. Zandvliet van Zelst': 1,
         'Léon van den Herik': 1,
         'F.F.M. van den Kieboom': 1,
         'Jessica van der Horst': 1,
         'Directiesecretaris': 1,
         'Klantencontact centrum': 1,
         'WOO-medewerker': 1,
         'P.F.J.M. Havermans': 1,
         'Team communicatie': 1,
         'Woo-contacterpsoon': 1,
         'Klantencontactcentrum': 1,
         'Fiscaal-Juridische zaken': 1,
         'R.S. Faber': 1,
         'Amber Enting': 1,
         'Edin Krkic': 1,
         'postbus@nl': 1,
         'Sanne Maring': 1,
         'Veerle Ultee': 1,
         'Wietse Bakker': 1,
         'Marcel Korving': 1,
         'Raïne Franck-Pouw': 1,
         'KCC gemeente Oisterwijk': 1,
         'Informatiespecialisten': 1,
         'info@com': 1,
         'Behandelend team Woo-verzoeken': 1,
         'Anne Schmidt': 1,
         'Freek Buijtelaar': 1,
         'J. Packbier': 1,
         'Janine Diekmeijer': 1,
         'Team informatiebeheer': 1,
         'Marleen Stuiver': 1,
         'Roy van Putten': 1,
         'Wouter Beelen': 1,
         'Rutger Nijhof': 1,
         'Elise Bos Eyssen': 1,
         'Yasmin Elbousaily': 1,
         'Woo-bureau': 1,
         'Stedelijk Team Openbaarheid': 1,
         'Doortje Lekkerkerk': 1,
         'Fauzia Khealiram': 1,
         'P.R. Veloo': 1,
         'A.J.W. Janssen': 1,
         'Jitske Schafraad': 1,
         'Bayram Kurt': 1,
         'N. Schelstraete': 1,
         'Henk Keijsers': 1,
         'Ard Schilder': 1,
         'Anne Bruins': 1,
         'Contactpersoon gemeente Vlissingen': 1,
         'Nward Zakarjan': 1,
         'Luca Frantzen': 1,
         'communicatie@nl': 1,
         'Woo-contactpersoon VrZW': 1,
         'Zehra Karakoç': 1,
         'Informatiemanager Dienstverlening': 1,
         'Griffier': 1,
         'Milou ': 1,
         'Francina ': 1,
         'Cindy Tsang': 1,
         'Leny van de Ketterij': 1,
         'Ramona Lemstra': 1,
         'Han Walhof': 1,
         'Juridische zaken': 1,
         'Thomas van der Klei': 1,
         'Woo-afhandeling': 1,
         'Alwine van Doornik': 1,
         'Erick Kraakman': 1,
         'Yvonne Visser': 1,
         'Rien Bal': 1,
         'Nikki Ganzeboom': 1,
         'https://nl/formulieren/contactformulier': 1,
         'Amanda Visser': 1,
         'Bé Wever': 1,
         'Meld en informatiepunt': 1,
         'Griffie': 1,
         'Jens Koning': 1,
         'Juridisch beleidsadviseur': 1,
         'Kijk op https://nl/woo-contactpersoon/ voor alle informatie': 1,
         'Joyce Bakkenes': 1,
         'R. Klerks': 1,
         'E. Lewandowski': 1,
         'R. Willems': 1,
         'Marcella Gommers': 1,
         'Gerda Bellomo-Dekker': 1,
         'Destiny Coenraad': 1,
         'Jacintha Wijngaarde': 1,
         'D. Nijholt': 1,
         'L. Ugurlu': 1,
         'secretariaat@nl': 1,
         'Klant Contact Center RoEntree!': 1,
         'Team Digitale Informatievoorziening': 1,
         'directiesecretaris': 1,
         'Veronique Gortemaker': 1,
         'Henk Meulendijks': 1,
         'Jannemarein Renout': 1,
         'Han Claus': 1,
         'Wiebrig Reitsma': 1,
         'O. Govers-Terschegget': 1,
         'L.J. van Duijn-Klok': 1,
         'Peter Bousardt': 1,
         'Kübra Güzel - Özcan': 1,
         'Kelly van Santen- Buijk': 1,
         'Kasper Janssen': 1,
         'Joost Meussen': 1,
         'N. de Ruiter': 1,
         'info@noardeast-nl': 1,
         'Maayke de Coninck': 1,
         'afdeling Juridische Zaken': 1,
         'A. Roosma': 1,
         'Woo-behandelaar Gezondheidsraad': 1,
         'Ramon van der Maas': 1,
         'Contactpersoon Woo': 1,
         'Yvonne Koffyberg': 1,
         'Team Communicatie': 1,
         'Alfred Klaver': 1,
         'Directiesecretariaat': 1,
         'Liesbeth Kooijman': 1,
         'Hekmat Naebkhel': 1,
         'Özhan Cinkiz': 1,
         'Lotte Brouwer': 1,
         'Ronald Michel Kooistra': 1,
         'Stefanie de Voogd': 1,
         'Contactcentrum': 1,
         'Infowoo@nl': 1,
         'Rob Andriessen': 1,
         'Luc Krekels': 1,
         'Afdeling Juridische zaken': 1,
         'Els de Jong': 1,
         'Contactfunctionaris': 1,
         'T. Lavania': 1,
         'J.C. Punt': 1,
         '0 70 348 75 10': 1,
         'C. van Ommeren': 1,
         'Provincieloket': 1,
         'Team Kwaliteit en control': 1,
         'Woo-contactfunctionaris': 1,
         'Tom Soomers,': 1,
         'Youssef Boudaghmas': 1,
         'C. Roethof': 1,
         'Woo contactpersoon Waterschap Limburg': 1,
         'Woo contactpersoon Waterschap Zuiderzeeland': 1,
         'Wil Mettes': 1,
         'Roderick Moolenaars': 1,
         'Administratief medewerker': 1,
         'M.I. Cazemier': 1,
         'Bestuurssecretaris': 1})
