Counter({'Ingekomen stukken': 18395,
         'Moties': 13918,
         'Raadsbrieven': 10888,
         'Raadsvragen': 9578,
         'Schriftelijke vragen': 8251,
         'Toezeggingen': 7733,
         'Brieven aan de raad': 7465,
         'Export': 6634,
         'Raadsinformatiebrieven': 4602,
         'Amendementen': 4358,
         'RSS': 4036,
         'Besluitenlijst B&W': 3141,
         'Collegebrieven': 2970,
         'Informatieve Stukken College': 1777,
         "Informatienota's": 1663,
         'Post aan de raad': 1503,
         'Collegebesluiten ter informatie': 1430,
         'Verslagen Raad': 1238,
         'Lijst Ingekomen Stukken': 1204,
         "Memo's": 1148,
         'Besluitenlijsten college': 1108,
         'Schriftelijke vragen en antwoorden': 1083,
         'Ingekomen stukken - College': 1080,
         'Uitnodigingen': 1054,
         'Artikel 43 vragen': 1012,
         'Technische vragen': 1005,
         'Besluitenlijsten B&W': 996,
         'Griffie-info documenten': 994,
         'Ingekomen stukken Cluster Sociaal': 987,
         'Artikel 44 vragen': 940,
         'Raadsvragen Schriftelijke': 892,
         'Raadsinfo': 876,
         'Notities ter info': 872,
         'Ingekomen stukken raad': 866,
         'Raadsvragen en antwoorden': 864,
         'Verslagen': 843,
         'Raadsbesluiten': 810,
         'export': 802,
         'B&W besluiten': 776,
         'Schriftelijke vragen art. 41': 729,
         "Raadsmemo's": 720,
         'Collegebesluiten': 646,
         'Toezeggingen Export': 645,
         'Verslagen M&S': 576,
         'Besluitenlijsten': 565,
         'Openbare besluitenlijsten college': 533,
         'Ingekomen stukken Cluster Bestuur': 487,
         'Stukkenstroom': 481,
         'Commissie informatiebrieven': 453,
         'Schriftelijke vragen (artikel 41 RvO)': 435,
         'Verslagen S&R': 406,
         'Brieven aan de raad - andere brieven': 371,
         'Besluitenlijst raad': 370,
         'College besluitenlijsten': 364,
         'Ingekomen stukken iBO': 356,
         'Collegestukken': 353,
         'Artikel 36 vragen': 349,
         'Brieven college aan de raad': 339,
         'Ingekomen stukken iBo': 339,
         'Archief moties/ toezeggingen/ art 44/ rappellijst': 334,
         'Genomen raadsbesluiten': 334,
         'Besluitenlijsten (B&W)': 330,
         'Informatie van het college': 329,
         "Brieven en memo's": 323,
         'RaadsvragenIbo': 321,
         'Memo actieve raadsinformatie': 320,
         'Brieven van derden aan de raad': 319,
         'Informatie voor de raad': 308,
         'Informatienota’s van het college': 308,
         'Moties en Amendementen': 308,
         'Schriftelijke vragen art. 18': 306,
         'moties export': 301,
         'Collegebrieven RSS': 300,
         'Dagmail': 300,
         'Dossiers': 300,
         'Archief tot maart 2015': 299,
         'Besluitenlijsten van de raad en commissie': 297,
         'Vraag en antwoord technische vragen art. 47 RvO': 290,
         'EXPORT': 290,
         'Griffie-info': 283,
         'Openbaar verslag en besluitenlijst B&W': 275,
         'Vragen Tussentijds': 274,
         'Schriftelijke vragen (art 33 RvO)': 269,
         'Beantwoorde raadsvragen': 267,
         'Rondvragen commissies': 263,
         'Besluitenlijst raadsvergadering': 248,
         'Moties WS export': 244,
         'Besluitenlijsten van het College Vastgestelde': 243,
         'Vastgesteld beleid': 234,
         'Verslagen Vragenuur': 233,
         'Besluitenlijsten van het college': 232,
         'Rekenkamercommissie': 230,
         'Vragen aan het college': 230,
         'Schriftelijke vragen art. 37': 219,
         'Toezeggingen Algemeen en ruimtelijk': 210,
         'Politieke vragen': 207,
         'Verslagen raad': 194,
         'Uitnodigingen gemeenteraad': 183,
         'LTA': 182,
         'Besluitenlijst B&W Druten': 178,
         'Getekende raadsbesluiten': 176,
         'Verslag Raad': 174,
         'Actuele Berichten': 170,
         'Besluitenlijst B&W Wijchen': 166,
         'Raadsvoorstellen': 161,
         'Informatieve vragen': 161,
         'getekende raadsbesluiten': 160,
         'Notulen': 158,
         'Besluitenlijsten raad': 158,
         'Brieven VNG': 142,
         'Moties en amendementen': 136,
         'Rekenkamer': 134,
         'BenW besluiten Website': 133,
         'Verslagen Monumentencommissie': 128,
         'Besluitenlijst commissie sociaal': 124,
         'Verbonden partijen': 121,
         ' Aanleveren vragen door fracties': 119,
         'Besluitenlijst Presidium': 118,
         'Besluitenlijst raadsvergaderingen': 116,
         'Nevenfuncties raadsleden': 114,
         'Vragen van raads- en commissieleden': 114,
         'Ingediende moties': 113,
         'Besluitenlijsten van de raad': 112,
         'Besluitenlijst commissie fysiek': 112,
         'Besluitenlijst commissie bestuur en middelen': 111,
         'Nevenfuncties commissieleden': 111,
         'Termijnagenda': 110,
         'Besluitenlijst Raad': 104,
         'Besluitenlijst': 93,
         'Artikel 39 vragen': 92,
         'Vragenhalfuurtje': 88,
         'Ingekomen stukken Raad (openbaar)': 88,
         'Verslag debat': 85,
         'Besluitenlijsten Politieke avond Westerveld': 85,
         'Raadsconsultaties': 84,
         'Besluitenlijst commissie Ruimtelijk Domein': 81,
         'Raadsvergadering RSS': 81,
         'Rekenkamerstukken': 79,
         'Schriftelijke vragen (art 39)': 79,
         'Besluitenlijsten gemeenteraad': 78,
         'Besluitenlijsten/Notulen Raad': 77,
         'Raadsvragen (RSS)': 75,
         'Uitzendingen raadsvergaderingen': 70,
         'Commissievergadering RSS': 69,
         'LTA NIEUW': 68,
         'Uitzendingen commissievergaderingen': 68,
         'Besluitenlijst commissie Algemene Zaken': 68,
         'besluitenlijst raad vastgesteld': 66,
         'Vergaderkalender': 64,
         'Artikel 41 RvO vragen en antwoorden': 63,
         'Adviezenlijsten Raadscommissie': 62,
         'Archief': 60,
         'Verslag presidium': 56,
         'Algemene informatie': 55,
         'Besluitenlijst raadscommissies': 54,
         ' Schriftelijke vragen RvO': 54,
         'Lijst ingekomen stukken': 54,
         'Aangenomen moties': 54,
         'Besluitenlijsten raadsvergaderingen': 53,
         'Agendacommissie / Presidium  RSS': 53,
         'Toezeggingen en moties': 52,
         'Verkiezingen': 51,
         'Vragen Coronavirus': 51,
         'Schriftelijke vragen (art. 36)': 49,
         'Besluitenlijst commissie Sociaal Domein': 48,
         'Rekenkamer rapporten': 47,
         'Raad besluitenlijst en verslag': 47,
         'Register opgeheven geheimhoudingen': 46,
         'Besluitenlijsten raad en commissies': 45,
         'Verslagen commissie Ruimtegebruik en Leefomgeving': 45,
         'Raadsbesluit': 45,
         'Lijst moties': 45,
         'Lijst toezeggingen': 45,
         'Artikel 32 vragen': 44,
         'besluitenlijst Presidium': 44,
         'Verslagen Samenleving en Bestuur': 40,
         'Overige openbaarmakingen Woo': 39,
         'Beantwoorde raadstoezegging': 39,
         'Besluitenlijsten Commissie Ruimte': 37,
         'Financiële documenten': 36,
         'Formatie': 36,
         'Gemeenteraadsverkiezingen 2022': 33,
         'Herindeling': 32,
         'Vergaderschema': 30,
         'Vergoedingen': 30,
         'Vughts Spiekbriefje': 29,
         'Financiële stukken': 28,
         'Geheimhoudingsregister': 27,
         'Verslagen Presidium': 27,
         'Llijst ingekomen stukken': 26,
         'Raadsnotitie': 24,
         'OZ Rekenkamercommissie': 22,
         'Omgevingswet': 21,
         'Besluitenlijsten gezamenlijke Commissie': 21,
         "Beleidsnota's": 21,
         'Verordeningen en regelingen': 20,
         'Woo-besluiten': 20,
         'Verslag Forum Stad en Samenleving ': 19,
         'Gemeenschappelijke regelingen': 19,
         'Nevenfuncties collegeleden': 19,
         'Besluitenlijsten Raadsvergaderingen': 18,
         'Rekenkamerrapporten iBo': 18,
         'Instrumenten BOB': 18,
         'Inwerkprogramma': 17,
         'Verordeningen Raad en Commissies': 17,
         'Toetsingskamer': 17,
         'rekenkameronderzoeken': 16,
         'Rekenkamerdocumenten': 16,
         'Beleidsdocumenten': 16,
         'Raadsbibliotheek': 15,
         'Rekenkamerrapporten': 15,
         'Actueel': 14,
         'Raadsonderwerpen': 14,
         'Commissie Ruimte verslag': 14,
         'Spiekbriefje': 14,
         'Verordeningen/reglementen': 13,
         'Verslagen commissie Financiën en Bedrijfsvoering': 13,
         'Uitnodigingen overkant': 13,
         'VNG Nieuws': 13,
         'Burgemeestersbesluiten': 12,
         'Aangeboden raadsvoorstellen': 12,
         'Verordeningen van de Raad': 12,
         'Rondom de Raad': 11,
         'Commissie Inwoners verslag': 11,
         'Verordeningen en gedragscode': 10,
         'Referendumcommissie': 10,
         'Besluitenlijsten Commissie B&S': 10,
         'Vastgestelde visies': 10,
         'Raadsdossiers': 9,
         'Verordeningen van de raad': 9,
         'Verantwoording fracties': 9,
         'Acties & toezeggingen': 9,
         'Burgerinitiatieven': 8,
         '1 Algemeen overzicht': 8,
         'Sollicitatiebrieven': 8,
         'Begroting': 8,
         'Ledenbrieven VNG': 8,
         'Besluitenlijst raadsvoorstellen': 7,
         'Initiatiefvoorstellen': 7,
         'Petities': 6,
         'Interpellatieverzoeken': 6,
         'Coalitievorming 2022': 5,
         'Voortgangslijst': 5,
         'Interne ingekomen stukken': 5,
         'Actielijsten commissie/raad': 4,
         'Toezeggingenlijst raad': 4,
         'Verslagen auditcommissie': 3,
         'Grote projecten': 3,
         'Raadsplanning': 2,
         'Arhi-procedure Scherpenzeel': 2,
         'Bestuurlijke vragen': 2,
         'Toezeggingen aan de raad': 2,
         'Verordeningen': 2,
         'Ontvangen raadsvoorstellen': 2,
         'Reglement van Orde': 2,
         'Nog te agenderen': 2,
         'Gasdossier': 2,
         'Informatiedossier': 1,
         'mid term verslag': 1,
         'Verzoek om inlichtingen': 1,
         'Nieuws van de gemeenteraad': 1,
         'Overzicht uitgevoerde moties': 1})
